module.exports = {
  content: ['index.html', 'scripts/**/*.js'],
  css: ['styles/styles.css'],
  output: 'styles/styles.purged.css',
  safelist: {
    standard: [
      /^tw-/,
      /^view-/,
      'active',
      'selected',
      'loading',
      /^inline_/,
      /-tw-/,
      /^btn-/,
      /^uploader-/,
      /^preview-/,
      /^mask-/,
      /^tool-/,
      /^brush-/,
      /^zoom-/,
      /^editor-/,
      /^text-/,
      /^bg-/,
      /^font-/,
      /^rounded-/,
      /^border-/,
      /^p-/,
      /^m-/,
      /^flex-/,
      /^grid-/,
      /^w-/,
      /^h-/,
      /^max-/,
      /^min-/,
      /^z-/,
      /^opacity-/,
      /^transition-/,
      /^duration-/,
      /^ease-/,
      /^hover:/,
      /^focus:/,
      /^disabled:/,
      /^md:/,
      /^lg:/,
      /^sm:/
    ],
    deep: [/data-active/],
    greedy: [/inline_/]
  },
  defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []
};
